Fix flashing delete modal
spatie/nova-backup-tool pull request #105
Opened 2021-04-03 19:13 UTC by quintenbuis

This fixes #85

Only downside it only really works when polling is set to a minimum of 2 in the config. When set to 1 it will flash for 1 / 2 times and then it stops. Any ideas how to fix this will be welcome!

2021-04-04 19:08 UTC, quintenbuis commented
Fixed issue with polling. Atleast when you don't have devtools open..

2021-04-05 08:22 UTC, freekmurze requested changes

2021-04-05 08:22 UTC, freekmurze commented on resources/js/components/BackupTool.vue
> +        toggleModal({ state }) {
I think `setModalVisibility` would be a better now, as you're not really toggling.

2021-04-05 08:43 UTC, freekmurze commented on resources/js/components/BackupTool.vue
> +        setModalVisibility({ state }) {
Instead of passing an object, passing a boolean would better simpler/better.

2021-04-05 10:54 UTC, merged

2021-04-05 10:54 UTC, freekmurze commented
Thanks!